### ISSUE TITLE
Change version of modified LittleProxy so that Maven doesn't confuse it with the "regular" littleproxy.

### ISSUE THREAD

**Issue by zerkz** [ganskef/LittleProxy-parent#1]
Hi,

I noticed that the version (and all identifiers of a dependency, like groupid and artifactid) defined in the POM of the modified LittleProxy (https://github.com/ganskef/LittleProxy/blob/master/pom.xml) are the same as the main repo of LittleProxy. The name is different, but I don't think its taken into account for dependency resolution/retrieval. 

Is there any way we could change the version so to something like "1.1.0-beta1-MITM_SNAPSHOT"? This way, once you mvn install LittleProxy-parent, you wouldn't have to worry about conflicts/downloading the "wrong" littleproxy.

Thanks!

**Comment by ganskef** [comment]
Hi Zack,

I'm not familiar with maven releases and I'm not familiar with the 
requirements of other projects like Lantern with LittleProxy. The 
LittleProxy-mitm project was a workaround solution for me.

I think, it should be created a branch with a new modular structure for 
LittleProxy, see #173. No modifications, modularization only, build and 
pull request for discussion. Next step could be to clean up the 
dependencies.

Regards Frank

Am 30.06.2015 um 18:11 schrieb Zack Whipkey:

**Comment by ganskef** [comment]
@zerkz I'm evaluating to release MITM with Maven. Do you have any suggestions.
- I've registered a groupId com.github.ganskef. It follows a naming convention from Sonatype since I haven't got a domain name.
- The dependency to ganskef/LittleProxy is removed from the master branch so it builds standalone. The offline facilities are moved into a branch.

**Comment by zerkz** [comment]
@ganskef 

That maven group ID looks to follow convention (although you could say "com" is usually used for commercial companies, whereas org is a little more for open source/non profit/school : see https://en.wikipedia.org/wiki/.org)

Nice job on the standalone thing!

**Comment by ganskef** [comment]
Hi Zack,

I've tried de.ganskef for a Maven groupId:

```
 https://issues.sonatype.org/browse/OSSRH-19795
```

They've stated:

   "You may also choose a groupId that reflects your project hosting, in 
this case, something like com.github.ganskef"

Regards Frank

Am 16.01.2016 um 17:36 schrieb Zack Whipkey:

**Comment by ganskef** [comment]
LittleProxy-mitm is in Maven Central and the offline feature uses a separate version, so I'm closing this issue.
